# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.0.0

# Adicione sua configuração de plug-ins kibana aqui
RUN kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.0.0/sentinl-v6.0.0.zip
# Exemplo: RUN instalação do plugin kibana <nome | url>
